spring:
  banner:
    location: classpath:banner.txt
  application:
    name: UMS
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: ums
    password: ums
    driver-class-name: oracle.jdbc.OracleDriver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:8443/realms/UMS/protocol/openid-connect/certs

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Tehran

logging:
  level:
    org:
      springframework:
      security: trace
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

sms:
  api-key: ${SMS_API_KEY}

server:
  port: 9999
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.p12
    key-store-type: PKCS12
    key-store-password: university-ms
    key-alias: ums
